# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Restart rsyslog
  become: true
  ansible.builtin.service:
    name: 'rsyslog'
    state: restarted
  notify:
    - 'Ensure permissions on all logfiles are configured'

- name: Ensure permissions on all logfiles are configured
  become: true
  ansible.builtin.command:
    cmd: 'find /var/log/ -type f -perm /g+wx,o+rwx -exec chmod g-wx,o-rwx "{}" +'
